### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-cid#1]
I don't have access currently to enable travis and circle. I requested the permissions via github.

**Comment by diasdavid** [comment]
done

![image](https://cloud.githubusercontent.com/assets/1211152/18830163/2c6c52e6-8412-11e6-8c54-6fd8af396707.png)

![image](https://cloud.githubusercontent.com/assets/1211152/18830182/3c91c412-8412-11e6-899f-e4916f840577.png)
